# Tasca 4: Pràctica amb programació numèrica

## Exercici 1
Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [1]:
import numpy as np

def estadisticos(array,imprimir=True):
    ''' La función estadisticos devuelve un diccionario con los principales estadísticos. 
     Si quieres verlos impresos en pantalla, llama la funcion con el parámetro imprimir = True'''
    if array.ndim!=1:
        print('Tienes que introducir un array de una dimensión, gracias.')
        return None
    else:
        resumen= {'media':np.mean(array),
            'varianza': np.var(array), 
            'Desviacion estandard':np.std(array), 
            'Minimo':np.min(array),
            '1er Cuartil':np.percentile(array,25),
            'Mediana':np.median(array),
            '3er Cuartil':np.percentile(array,75),
            'Maximo':np.max(array)}
        if imprimir:
            for i,j in resumen.items():
                print(i,': ',j)
    
    return resumen

In [2]:
x=np.random.normal(0,1,(50))
y=np.arange(50)
z=y.reshape(25,2)

In [3]:
estadisticos(x)
estadisticos(y,imprimir=False)
estadisticos(z)

media :  0.01620090370558506
varianza :  1.2428957587337397
Desviacion estandard :  1.114852348400334
Minimo :  -2.428059033911728
1er Cuartil :  -0.7056545263211564
Mediana :  0.009850953807229623
3er Cuartil :  0.8518074347167437
Maximo :  1.8865326371462785
Tienes que introducir un array de una dimensión, gracias.


## Exercici 2
Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [28]:
def matriz_cuadrada(N):
    return np.random.randint(0,100,size=(N,N))

In [29]:
matriz_cuadrada(10)

array([[70,  3, 25, 37, 89,  1, 78, 33, 68, 47],
       [17, 86, 55, 17, 40, 97, 22,  2, 27, 39],
       [58, 17, 41, 21, 48, 55, 17, 77, 59, 52],
       [18,  7, 16, 25, 48, 36, 60, 35, 91, 30],
       [82, 12, 23, 16, 47, 19,  8, 56, 45, 79],
       [ 3, 91, 25, 68, 76, 93, 98, 15, 29, 28],
       [78, 86, 45, 36, 43, 47, 67,  3, 19, 86],
       [91, 95, 68, 74, 91, 97, 11, 46,  9, 26],
       [82, 22, 90, 42, 63, 51, 75, 12,  4, 83],
       [51,  2, 30, 86, 58, 41, 66, 17,  4, 53]])

## Exercici 3
Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.

In [8]:
tabla=np.arange(20).reshape(5,4)
tabla

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [14]:
suma_filas=tabla.sum(axis=1)
suma_columnas=tabla.sum(axis=0)
print(suma_filas)
print(suma_columnas)

[ 6 22 38 54 70]
[40 45 50 55]


## Exercici 4
Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

El coeficiente de correlación es una medida de la dependencia lineal de dos distribuciones. A diferencia de la covarianza, el coeficiente de correlación no depende de la escala de magnitud de las distribuciones, pudiendo tomar valores entre -1 y 1. Valores próximos a cero indican que apenas existe relación lineal entre las distribuciones, mientras que cuanto más nos acerquemos a 1 o -1 mayor dependencia lineal.

Valores positivos indican que la relación es directa, es decir cuando aumenta una variable la otra también. Por otro lado, valores negativos indican una dependencia de tipo inverso, al aumentar una variable la otra disminuye.

El coeficiente de regresión se calcula con la siguiente fórmula:

$$ coef·R=\frac{Cov_{XY}}{\sqrt{Var_X·Var_Y}} $$


In [15]:
X=np.array([2,3,6,8,10])
Y=np.array([4,5,10,11,15])

In [51]:
# Función que calcula manualmente el coeficiente R

from math import sqrt
def coeficiente_R(X,Y):
    Varianza_X=((X-X.mean())**2).sum()/len(X)
    Varianza_Y=((Y-Y.mean())**2).sum()/len(Y)
    Covarianza_XY=((X-X.mean())*(Y-Y.mean())).sum()/len(X)
    Coef_R=Covarianza_XY/sqrt(Varianza_X*Varianza_Y)
    return Coef_R

In [50]:
coeficiente_R(X,Y)

0.9899318950283527

In [48]:
# Utilizando la función de numpy corrcoef que devuelve matriz de correlación
np.corrcoef(X,Y)

array([[1.       , 0.9899319],
       [0.9899319, 1.       ]])